<a href="https://colab.research.google.com/github/JonathonLeiding/introductory_neural_network/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import torch
import numpy as np

In [22]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [23]:
tensor_a + tensor_b  #~Matrix addition with position

tensor([ 6,  8, 10, 12])

In [24]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
#Subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [26]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [27]:
#Multiplication

In [28]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [29]:
torch.mul(tensor_a,tensor_b)


tensor([ 5, 12, 21, 32])

In [30]:
torch.multiply(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
# Division

In [31]:
tensor_a/tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [32]:
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [33]:
# Modulus/Remainder

In [34]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [35]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# Exponents

In [36]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [37]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
# Other long hand syntax

In [38]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Reassignment

In [39]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

Weird underscore after function is reassignment for some functions