<a href="https://colab.research.google.com/github/JonathonLeiding/introductory_neural_network/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensors**



*   Basically a multi-dimensional matrix, like a Numpy Array, but they are built to work better with GPUs than CPUs
*   Particularly helpful because GPUs can train models dozens of times faster than CPUs
*   default data is float32



In [1]:
import torch
import numpy as np

## **Numpy Arrays**

In [2]:
np1 = np.random.rand(3,4)
np1

array([[0.27864894, 0.44484001, 0.07788115, 0.774109  ],
       [0.73706741, 0.6797807 , 0.42131226, 0.04911356],
       [0.23764371, 0.36213124, 0.63004261, 0.4235711 ]])

In [3]:
np1.dtype


dtype('float64')

## **Tensors**

In [4]:
tensor2d = torch.randn(3,4)
tensor2d

tensor([[ 0.2764, -0.3027,  0.8221,  0.2007],
        [ 1.5648,  0.7165,  1.2533, -0.8576],
        [-0.1809, -0.5543,  0.1054,  1.0086]])

In [6]:
tensor3d = torch.randn(2,3,4)
tensor3d

tensor([[[ 0.4333, -0.9978, -0.4683,  0.7104],
         [ 1.0107,  1.3716, -0.2769,  0.6708],
         [-0.5832, -1.0524,  1.4361, -0.5404]],

        [[-0.9527, -0.0833, -1.1006, -0.7809],
         [-0.0779, -1.8803, -0.6936, -0.3216],
         [ 0.6006,  1.8377,  0.1070, -1.8299]]])

In [7]:
## Create tensor out of Numpy away
tensor_covt = torch.tensor(np1)
tensor_covt

tensor([[0.2786, 0.4448, 0.0779, 0.7741],
        [0.7371, 0.6798, 0.4213, 0.0491],
        [0.2376, 0.3621, 0.6300, 0.4236]], dtype=torch.float64)