<a href="https://colab.research.google.com/github/JonathonLeiding/introductory_neural_network/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Reshape but don't know how many total elts
my_torch2 = torch.arange(15)
my_torch2 = my_torch2.reshape(5,-1)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [ ]:
my_torch2.reshape(-1,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5 = torch.arange(10)
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5[0] = 4141
my_torch5

tensor([4141,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_torch6

tensor([[4141,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
my_torch7 = torch.arange(10, 20)
my_torch7

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
my_torch7[7]

tensor(17)

In [ ]:
my_torch8 = torch.arange(18).reshape(9,2)
my_torch8

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17]])

In [ ]:
my_torch8[:,1]

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [ ]:
my_torch9 = torch.arange(18).reshape(2,9)
my_torch9

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [ ]:
my_torch9[1, :]

tensor([ 9, 10, 11, 12, 13, 14, 15, 16, 17])